image:
  repository: questdb/questdb
  pullPolicy: IfNotPresent
  tag: 6.4.3

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

questdb:
  config:
    enabled: true
    options:
       shared.worker.count: 2

service:
  annotations: {}
  type: ClusterIP
  port: 9000
  expose:
    postgresql:
      enabled: true
      port: 8812
    influxdb:
      enabled: true
      port: 9009

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  storageClass: gp2-retain

ingress:
  enabled: false

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
