name: Deploy to Production

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: SSH to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DOMAIN }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: 'cd ax-DB/ &&
          git fetch &&
          git checkout ${{ steps.extract_branch.outputs.branch }} &&
          git pull &&
          echo App Deployed ${{ steps.extract_branch.outputs.branch }} to Production'
